Whi 81
whitelabel-lat/landing-pages-valeia pull request #1
Opened 2024-10-30 20:02 UTC by tauronro

2024-10-30 20:42 UTC, danilocha requested changes

2024-10-30 20:42 UTC, danilocha commented on src/components/layout/main/HomeValeIa.js
> +  console.log(data,'data <---');
por fa borra los logs

2024-10-30 20:42 UTC, danilocha commented on src/components/sections/abouts/AboutValeia1.js
> +  console.log(fullImageUrls,'fullImageUrls');
borrar

2024-10-30 20:42 UTC, danilocha commented on src/components/sections/abouts/AboutValeia1.js
> +                <Image
quiza si sea mejor usar img en vez de image, es mas optimo pero gasta mas recursos del serverless, lo que encarece el servicio de vercel

2024-10-31 17:02 UTC, tauronro commented on src/components/sections/abouts/AboutValeia1.js
> +                <Image
Pues es que la verdad estaba tratando de usarlo con img, pero si usamos el componente Image el renderizado de las images es mas optimo, de igual manera ya ajuste todos los campos de imagenes con el componente Image

2024-10-31 17:11 UTC, tauronro commented on src/components/layout/main/HomeValeIa.js
> +  console.log(data,'data <---');
ya se borraron

2024-10-31 17:41 UTC, tauronro commented on src/components/sections/abouts/AboutValeia1.js
> +                <Image
tambien es mejor practica manejar el componente Image que usar la etiqueta <img>

2024-11-07 23:57 UTC, danilocha approved these changes

2024-11-13 20:56 UTC, danilocha commented on src/components/sections/abouts/AboutValeia1.js
> +                <Image
si y no usar el componente image, gasta recursos de computo que nos van a combrar y es super caro

2024-11-13 21:37 UTC, merged